services:
  web:
    extends:
      file: compose.yaml
      service: web
    command: ["pnpm", "run", "dev"]
    environment:
      # Pick from list of supported models here:
      # https://mastra.ai/models/providers/anthropic#models
      - LLM_MODEL=anthropic/claude-3-5-sonnet-20241022
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes: # for hot-reloading during development
      - ./app:/app
      - /app/node_modules
